# Introductory applied machine learning (INFR10069)

# Lab 1: Introduction

In the first part of this lab we will set-up a working environment for the IAML course. In the second part we will introduce some packages we will be using throughout the course.

# Setting up for DICE

Within this course we will be using Python along with a few open-source libraries (packages). These packages cannot be installed directly, so we will have to create a virtual environment. We are using virtual enviroments to make the installation of packages and retention of correct versions as simple as possible. You can read [here](https://virtualenv.pypa.io/en/stable/) if you want to learn about virtual environments, but this is **not** neccessary for this tutorial.

Now open a terminal and follow these instructions. We are expecting you to enter these commands in **one-by-one**. Waiting for each command to complete will help catch any unexpected warnings and errors. Please read heed any warnings and errors you may encounter. We are on standby in the labs to help if required.

1. Change directory to home and create a virtual enviroment
```bash
cd
virtualenv --distribute virtualenvs/iaml_env  # Creates a virtual environment called iaml_env
```
   
2. Navigate to and activate the virtual enviroment (you will need to activate the virtual environment every time you open a new terminal - this adds the correct python version with all installed packages to your system's `$PATH` environment variable)
```bash
cd virtualenvs/iaml_env
source ./bin/activate  # Activates the environment, your shell prompt should now 
                          # change to reflect you are in the `iaml_env` enviornment
```

3. Install all the python packages we need (once the correct virtual environment is activated, pip install will install packages to the virtual environent - if you're ever unsure which python you are using, type `which python` in the terminal) **WATCH FOR WARNINGS AND ERRORS HERE**. We have split these commands up to encourage you to enter them one-by-one.
   
    * `pip install -U setuptools  # The -U flag upgrades the current version`
    * `pip install -U pip`
    * `pip install yolk`
    * `pip install jupyter`
    * `pip install numpy`
    * `pip install scipy`
    * `pip install matplotlib`
    * `pip install pandas`
    * `pip install statsmodels`
    * `pip install scikit-learn`
    * `pip install seaborn`

You should now have all the required modules installed. Our next step is to make a new directory where we will keep all the lab notebooks, datasets and assignments. Within your terminal:

1. Navigate back to your home directory
    * `cd`
1. Make a new directory and navigate to it
    * `mkdir iaml_2016`
    * `cd iaml_2016`

Now you have two options:

1. We recommend that you directly download a .zip file from https://github.com/agamemnonc/iaml which will contain everything you need and save it in the folder you have just created. You can do this from the terminal by typing:
    * `wget https://github.com/agamemnonc/iaml/archive/master.zip`
    * `unzip master.zip`
2. If **and only if** you are familiar and confident with using Git/GitHub, you can initiliaze a git directory, add the above repo as remote and pull everything into your local directory. Please use this option only if you really know what you are doing. Unfortunately, we won't be able to provide you with Git/Github support if you run into issues with syncing and using version control in general. 

Once you have downloaded the material, you are now ready to start working in the Jupyter environment. First you need to activate the `iaml_env` environment and start a Jupyter Notebook session from within the folder where the material is stored. **Note that you will have to follow this procedure for all labs and assignments.**

1. Navigate home and ensure the `iaml_env` virtualenv is activated
    * `cd`
    * `source virtualenvs/iaml_env/bin/activate` (Activate environment)
1. Enter the directory you downloaded the course material
    * `cd iaml_2016/iaml-master`
1. Start a jupyter notebook
    * `jupyter notebook`
1. This should automatically open your browser
    * Click on `01_Lab_1_Introduction.ipynb` to open it

# Setting up for personal machine (Windows / OS X / Ubuntu)

If you are using a personal machine, you can choose whether to do as above or use the Anaconda distribution (Python version 2.7, choose the appropriate installer according to your operating system). Anaconda is a standard set of packages used in scientific computing which the Anaconda team curate to keep them consistent.

Once the installation is complete, we need to install the Seaborn package which is the only one not included in the distribution. It's also recommended that you set up a virtual environment for this project. This way, if you update anything in your anaconda base install, this virtual environment will remain unchanged. To create a virtual environment called `iaml`, open a Terminal (or Command Prompt window if you are running Windows) and type:

```bash
conda create -n iaml python=2.7 anaconda seaborn=0.7.0
```

Don't forget to activate the virtual environment every time you begin work from a new terminal:

```bash
source activate iaml
```

Once you have finished installed everything, open a terminal (or Command Prompt in Windows), navigate to the folder where you have downloaded the course material and type:

```bash
jupyter notebook
```

Then click on `01_Lab_1_Introduction.ipynb` to open it.

# Introducing main packages

In the following section we introduce the main **packages** we will be using in this course. If you think that you are already familiar with the packages outlined below you are free to skip this section. We do advise you, however, to go quickly through this tutorial to make sure that you are familiar with all the tools you will need for the rest of the course.

The packages that we will use are the following:
* [numpy:](http://www.numpy.org/) scientific computing by using array objects


* [pandas](http://pandas.pydata.org/): data structures and data analysis tools


* [matplotlib](http://matplotlib.org/): plotting library (similar to MATLAB's plot interface)


* [seaborn](https://seaborn.github.io/): data visualisation library which works on top of matplotlib

Throughout the course, we will also make heavy use of [scikit-learn](http://scikit-learn.org/stable/) which is a machine learning library implementing many learning algorithms and useful tools. This is introduced in Lab 2.

## IPython / Jupyter environment

Basic knowledge of `python` and working with `notebooks` in the Jupyter environment is assumed for this course. If you haven't used python before, you are strongly advised to familiarise yourselves with basic python syntax and working in the Jupyter environment. There are many excellent tutorials available on the web and you can choose the ones you like the most. If you are not sure which ones to choose, these are good starting points:

[Introduction to Python for scientific computing](http://bebi103.caltech.edu/2015/tutorials/t1a_intro_to_python.html)

[Introduction to Jupyter notebooks](http://bebi103.caltech.edu/2015/tutorials/t0b_intro_to_jupyter_notebooks.html)

[Python/Numpy tutorial](http://cs231n.github.io/python-numpy-tutorial/#python)
(A large part of Lab 1 is based on this tutorial)


## Line magics

Sometimes we might want to connect to the same notebook kernel from multiple frontends. This is useful for excecuting quick calculations, or checking objects currently stored in the kernel, without having to create a new cell in the notebook.

The `%connect_info` line magic displays the information necessary to connect another frontend to the Notebook kernel.

In [1]:
%connect_info

{
  "stdin_port": 58496, 
  "ip": "127.0.0.1", 
  "control_port": 58497, 
  "hb_port": 58498, 
  "signature_scheme": "hmac-sha256", 
  "key": "c4a8686f-7d1e-482a-9cb4-c5bdfae9788d", 
  "kernel_name": "", 
  "shell_port": 58494, 
  "transport": "tcp", 
  "iopub_port": 58495
}

Paste the above JSON into a file, and connect with:
    $> jupyter <app> --existing <file>
or, if you are local, you can connect with just:
    $> jupyter <app> --existing kernel-7113b22d-50a0-42eb-b558-eb9775e6d5ad.json
or even just:
    $> jupyter <app> --existing
if this is the most recent Jupyter kernel you have started.


## Tab completion

Tab completion is a powerful method of finding out objects attributes and available methods.

Let's see an example of this by using a Python [list](http://www.tutorialspoint.com/python/python_lists.htm). We will create a list and then you can see what methods are available by typing the list name followed by `.` and then hitting the < Tab > key. Then you can access any method's help documentation by hitting the method's name followed by `?`

In [2]:
l = [1, 4.2, 'hello']
print(l)

[1, 4.2, 'hello']


In [3]:
l.append?

## Import packages

Before we start, we need to import the packages that we will be using later. If you are having trouble importing any of these packages make sure that these are properly installed. If you still encounter issues, refer to Installing instructions.

In [4]:
from __future__ import division, print_function # Makes division and printing work like python 3 (we're using 2)
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

## Numpy introduction

Numpy is a powerful scientific computing library. The fundmental object is the (n-dimensional) numpy array and the library provides a collection of tools for working with such arrays. If you are already familiar with MATLAB you might find this [tutorial](https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html) useful. 

The following Numpy introduction is largely based on this [tutorial](http://cs231n.github.io/python-numpy-tutorial/#numpy).

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a [tuple](http://www.tutorialspoint.com/python/python_tuples.htm) of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension. *N.B. this use of the word 'rank' is not the same as the meaning in linear algebra.*

We can initialize numpy arrays from nested Python [lists](http://www.tutorialspoint.com/python/python_lists.htm), and access elements using square brackets:

In [5]:
import numpy as np
a = np.array([1, 2, 3])  # Create a rank 1 array (i.e. vector)
print('Array a:', a)

Array a: [1 2 3]


In [6]:
print(type(a))                    # Prints the type of object a (array)

<type 'numpy.ndarray'>


In [7]:
print(a.shape)                    # Prints the number of elements for each dimension

(3,)


In [8]:
print(a[0], a[1], a[2])           # Index array

1 2 3


In [9]:
a[0] = 5                          # Change an element of the array

In [10]:
print(a)                          # Prints the whole array

[5 2 3]


In [11]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array

In [12]:
print(b.shape)                   

(2, 3)


In [13]:
print(b[0, 0], b[0, 1], b[1, 0])

1 2 4


At this point it worth noting -in case you didn't know already- that Python follows [0-based indexing](https://en.wikipedia.org/wiki/Zero-based_numbering) (as opposed to MATLAB which follows 1-based indexing).

In an ipython notebook you can just run a cell with an object name and ipython will try to print it. For example, execute the below cell:

In [14]:
a

array([5, 2, 3])

### Create arrays

We have many options here:

In [15]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)                    # Prints "[[ 0.  0.]
                     #          [ 0.  0.]]"
    

[[ 0.  0.]
 [ 0.  0.]]


In [16]:
b = np.ones((1,2))   # Create an array of all ones
print(b)                    # Prints "[[ 1.  1.]]"

[[ 1.  1.]]


In [17]:
c = np.full((2,2), 7) # Create a constant array
print(c)                     # Prints "[[ 7.  7.]
                      #          [ 7.  7.]]"

[[ 7.  7.]
 [ 7.  7.]]


/Users/wangwen/anaconda3/envs/iaml/lib/python2.7/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [18]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)                    # Prints "[[ 1.  0.]
                     #          [ 0.  1.]]"
    

[[ 1.  0.]
 [ 0.  1.]]


In [19]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)                           # Might print "[[ 0.91940167  0.08143941]
                            #               [ 0.68744134  0.87236687]]"
    

[[ 0.69685011  0.89617841]
 [ 0.77420328  0.43520648]]


In [20]:
some_list = [1, 4, 6, 8]
f = np.array(some_list, dtype=float) # Create an array from a list. Also sets the array type to float
print(f)

[ 1.  4.  6.  8.]


### Array indexing

Slicing is the most common way to index arrays. This works in a similar way to indexing python lists. 

There are also other options, such as integer and boolean array indexing.

In [21]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [23]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array. This is called 
print(a[0,1])  # Prints "2"

2


In [24]:
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0,1])          # Prints "77"

77


### Array datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [25]:
x = np.array([1, 2])  # Let numpy choose the datatype
print(x.dtype)       

int64


In [26]:
x = np.array([1.0, 2.0])  # Let numpy choose the datatype
print(x.dtype)             

float64


In [27]:
x = np.array([1, 2], dtype=np.int64)  # Force a particular datatype
print(x.dtype)                 

int64


### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [28]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print('x = ',x)
print('y = ',y)

x =  [[ 1.  2.]
 [ 3.  4.]]
y =  [[ 5.  6.]
 [ 7.  8.]]


In [29]:
# Elementwise sum, equivalent expressions:
print('x + y =')
print(x + y)
print(np.add(x, y))

x + y =
[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [30]:
# Elementwise difference, equivalent expressions:
print('x-y:')
print(x - y)
print(np.subtract(x, y))

x-y:
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [31]:
# Elementwise product, equivalent expressions:
print('x*y:')
print(x * y)
print(np.multiply(x, y))

x*y:
[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


In [32]:
# Elementwise division, equivalent expressions:
print('x/y:')
print(x / y)
print(np.divide(x, y))

x/y:
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [33]:
# Elementwise square root
print('Square root of x:')
print(np.sqrt(x))

Square root of x:
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. `dot` is available both as a function in the numpy module and as an instance method of array objects:

In [34]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [35]:
# Inner product of vectors, equivalent expressions
print(np.dot(v, w))

219


In [36]:
# Matrix / vector product, equivalent expressions
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [37]:
# Matrix / matrix product, equivalent expressions
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Mathematical functions

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [38]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [39]:
np.sum(x)  # Compute sum of all elements

10

In [40]:
np.sum(x, axis=0)  # Compute sum of each column

array([4, 6])

In [41]:
np.sum(x, axis=1)  # Compute sum of each row

array([3, 7])

You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the `T` attribute of an array object:

In [42]:
x = np.array([[1,2], [3,4]])
print(x)

[[1 2]
 [3 4]]


In [43]:
x.T

array([[1, 3],
       [2, 4]])

In [44]:
np.transpose(x) # Equivalent expression

array([[1, 3],
       [2, 4]])

In [45]:
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)  # Prints "[1 2 3]"

[1 2 3]


In [46]:
print(v.T)  # Prints "[1 2 3]"

[1 2 3]


### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. 

In [47]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [48]:
print('x shape:', x.shape)
print('v shape:', v.shape)
print('y shape:', y.shape)

x shape: (4, 3)
v shape: (3,)
y shape: (4, 3)


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
The arrays can be broadcast together if they are compatible in all dimensions.
After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.

### Numpy documentation

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the numpy reference to find out much more about numpy.

### Numpy exercises

The following short exercises test your understanding of simple -yet important- numpy properties and functions. Make sure you can complete them and feel free to advise the official [documentation](http://docs.scipy.org/doc/) should you need it.

#### ========== Question 1 ==========
Print your numpy version.

In [50]:
print("Numpy version: ", np.__version__)


Numpy version:  1.11.1


#### ========== Question 2 ==========
Create a null vector of size 5.

In [54]:
a = np.zeros(15)
print(a)


[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


#### ========== Question 3 ==========
Create a null vector of size 5 and integer type. Set the third element is 1.

In [55]:
# Your code goes here
a = np.zeros(15)
a[2] = 1
print(a)


[ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


#### ========== Question 4 ==========
Create a vector ranging from 0 to 9.

In [56]:
# Your code goes here
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### ========== Question 5 ==========
Create a vector ranging from 10 to 29.

In [57]:
a = np.arange(10,29)
print(a)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28]


#### ========== Question 6 ==========
Create a vector ranging from 0 to 9 and reverse it.

In [61]:
a = np.arange(10)
print(a.reverse())


AttributeError: 'numpy.ndarray' object has no attribute 'reverse'

#### ========== Question 7 ==========
Create a null matrix of size (5,3).

In [63]:
a=np.zeros(15).reshape(5,3)
print (a)


[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


#### ========== Question 8 ==========
Crate a 3 X 3 matrix ranging from 0 to 8 and print its transpose.

In [67]:
a=np.arange(0,9).reshape(3,3)
print (a.T)




[[0 3 6]
 [1 4 7]
 [2 5 8]]


#### ========== Question 9 ==========
Create a 3 X 3 identity matrix.

In [68]:
a = np.eye(3)
print(a)


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### ========== Question 10 ==========
Create a 2 X 2 X 2 array with random values (drawn from a normal distribution).

In [69]:
# Your code goes here
a = np.random.randn(2,2,2)
print(a)


[[[ 1.36304853 -0.18068289]
  [ 2.48056421 -1.35259631]]

 [[-0.36592646 -0.5868452 ]
  [-0.34489636 -1.05084352]]]


#### ========== Question 11 ==========
Create a 5 x 4 array with random values and find the minimum and maximum values.

In [70]:
# Your code goes here
a = np.random.randn(2,2,2)
print(np.min(a))




-0.92483853496


#### ========== Question 12 ==========
Find the mean value of the array in 11.

In [ ]:
# Your code goes here


#### ========== Question 13 ==========
Find the row means of the array in 11.

In [ ]:
# Your code goes here


#### ========== Question 14 ==========
Find the column means of the array in 11.

In [ ]:
# Your code goes here


#### ========== Question 15 ==========
Create a list with elements 2.2, 3.5, 0, 4, 0. and convert into numpy array. Find the indices of non-zero elements.

In [ ]:
# Your code goes here


#### ========== Question 16 ==========
Crate two random matrices of shape (5,4) and (4,2). Print their matrix product.

In [ ]:
# Your code goes here


#### ========== Question 17 ==========
Crate a random matrix of shape (5,3) and a random vector of size 3. Use broadcasting to add the two arrays.

In [ ]:
# Your code goes here


## Pandas introduction

Pandas is a library for data manipulation and analysis. There are two fundamental data structures in pandas: the **Series** and **DataFrame** structures which are built on top of NumPy arrays.

The following introduction is largely based on this [tutorial](http://www.gregreda.com/2013/10/26/intro-to-pandas-data-structures/). Another useful referece is the [Pandas introduction to data structures](http://pandas.pydata.org/pandas-docs/stable/dsintro.html). Pandas is well documented and you will find good information about all methods and structures in the [API reference](http://pandas.pydata.org/pandas-docs/stable/api.html)

### Series

A **Series** a one-dimensional object (similar to a vector). Each element has a corresponding *index*. By default the indices range from 0 to N, where N is the length of the Series.

In [71]:
# First we need to import the pandas package
import pandas as pd

In [72]:
# Let's create a Series by passing in a list without specifying the indices.
s = pd.Series([1, 4.2, 'Hello'])
print(s)

0        1
1      4.2
2    Hello
dtype: object


In [73]:
# Now, let's specify the indices explicitly
s = pd.Series([1, 4.2, 'Hello'], index=['A', 'B', 'C'])
print(s)

A        1
B      4.2
C    Hello
dtype: object


In [74]:
# Indexing the Series
s['B']

4.2

In [75]:
# We can also index by using boolean logic
s[s>2]

B      4.2
C    Hello
dtype: object

### DataFrame

A DataFrame is a tabular data structure comprised of rows and columns. You can also think of the DataFrame as a collection of Series objects that share an index. 

#### Creating DataFrame structures

We can create an empty DataFrame by specifying the column names. Then we can insert data row by row.

In [76]:
df = pd.DataFrame(columns=['Gender', 'Age', 'Height', 'Weight'])
print(df)

Empty DataFrame
Columns: [Gender, Age, Height, Weight]
Index: []


In [77]:
# Now let's add an observation
df.loc[0] = ['Male', 23, 180, 73] # Note how we used .loc to specify the index
df.loc['A'] = ['Female', 27, 167, 59]
df

Gender   Age  Height  Weight
0    Male  23.0   180.0    73.0
A  Female  27.0   167.0    59.0

#### Creating DataFrame from other structures

You can also create a dataframe from:
* Dict of 1D ndarrays, lists, dicts, or Series
* 2-D numpy.ndarray
* Structured or record ndarray
* A Series
* Another DataFrame

For example:

In [79]:
# Create a DataFrame from a list
some_list = [['Male', 23, 180, 73], ['Female', 27, 167, 59]]
df = pd.DataFrame(some_list, index=[0, 'A'], columns=['Gender', 'Age', 'Height', 'Weight'])
print(df)

   Gender  Age  Height  Weight
0    Male   23     180      73
A  Female   27     167      59


In [80]:
# Create a DataFrame from a dictionary
some_dict = {0:['Male', 23, 180, 73], 'A':['Female', 27, 167, 59]}
df2 = pd.DataFrame.from_dict(some_dict, orient='index')
df2.columns = ['Gender', 'Age', 'Height', 'Weight']
print(df2)

   Gender  Age  Height  Weight
0    Male   23     180      73
A  Female   27     167      59


In [81]:
# By default, dictionary keys are assumed to be the column headers, above we
# explicitly made keys the row index using the `orient` argument. Below
# We transpose using the `.T` method
df3 = pd.DataFrame({0:['Male', 23, 180, 73], 'A':['Female', 27, 167, 59]}).T
df3.columns = ['Gender', 'Age', 'Height', 'Weight']
print(df3)

   Gender Age Height Weight
0    Male  23    180     73
A  Female  27    167     59


#### Loading a CSV into a DataFrame

Most commonly we create DataFrame structures by reading csv files. To run the following piece of code you need to download the datasets associated with the course and place them in a subdirectory called "datasets" under the same directory that your notebooks are located. Alternatively, you can specify the full path of the .csv file.

In [82]:
cpu_loc = os.path.join(os.getcwd(), 'datasets', 'cpu.csv')
cpu = pd.read_csv(cpu_loc)
cpu.head() # Head shows the first 10 elements (unless specified otherwise) of the DataFrame

vendor   MYCT    MMIN     MMAX   CACH  CHMIN  CHMAX    ERP
0  adviser  125.0   256.0   6000.0  256.0   16.0  128.0  199.0
1   amdahl   29.0  8000.0  32000.0   32.0    8.0   32.0  253.0
2   amdahl   29.0  8000.0  32000.0   32.0    8.0   32.0  253.0
3   amdahl   29.0  8000.0  32000.0   32.0    8.0   32.0  253.0
4   amdahl   29.0  8000.0  16000.0   32.0    8.0   16.0  132.0

You should see that each observation in our dataset comprises 8 measurements (attributes).

#### Basic methods
* `head(N)`: displays the first N elements of the DataFrame
* `tail(N)`: displays the last N elements of the DataFrame
* `info()`:  displays basic information about the variables
* `describe()`: displays summary statistics of the data

Execute the following cells and observe the outputs.

In [83]:
cpu.tail(5)

vendor   MYCT    MMIN    MMAX  CACH  CHMIN  CHMAX   ERP
204  sperry  124.0  1000.0  8000.0   0.0    1.0    8.0  37.0
205  sperry   98.0  1000.0  8000.0  32.0    2.0    8.0  50.0
206  sratus  125.0  2000.0  8000.0   0.0    2.0   14.0  41.0
207    wang  480.0   512.0  8000.0  32.0    0.0    0.0  47.0
208    wang  480.0  1000.0  4000.0   0.0    0.0    0.0  25.0

In [84]:
cpu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 8 columns):
vendor    209 non-null object
MYCT      209 non-null float64
MMIN      209 non-null float64
MMAX      209 non-null float64
CACH      209 non-null float64
CHMIN     209 non-null float64
CHMAX     209 non-null float64
ERP       209 non-null float64
dtypes: float64(7), object(1)
memory usage: 13.1+ KB


In [85]:
cpu.describe()

MYCT          MMIN          MMAX        CACH       CHMIN  \
count   209.000000    209.000000    209.000000  209.000000  209.000000   
mean    203.822967   2867.980861  11796.153110   25.205742    4.698565   
std     260.262926   3878.742758  11726.564377   40.628722    6.816274   
min      17.000000     64.000000     64.000000    0.000000    0.000000   
25%      50.000000    768.000000   4000.000000    0.000000    1.000000   
50%     110.000000   2000.000000   8000.000000    8.000000    2.000000   
75%     225.000000   4000.000000  16000.000000   32.000000    6.000000   
max    1500.000000  32000.000000  64000.000000  256.000000   52.000000   

            CHMAX          ERP  
count  209.000000   209.000000  
mean    18.267943    99.330144  
std     25.997318   154.757102  
min      0.000000    15.000000  
25%      5.000000    28.000000  
50%      8.000000    45.000000  
75%     24.000000   101.000000  
max    176.000000  1238.000000

#### Selection

You can think of a DataFrame as a group of Series that share an index (in this case the column headers). This makes it easy to select specific **columns**.

In [86]:
cpu['MMAX'].head(5) # Display the first 5 elements

0     6000.0
1    32000.0
2    32000.0
3    32000.0
4    16000.0
Name: MMAX, dtype: float64

In [87]:
type(cpu['MMAX'])   # This is a Series 

pandas.core.series.Series

To select multiple columns we simple need to pass a list of column names. The resulting object is another DataFrame.

In [88]:
cpu[['MMIN', 'MMAX']].head(7)

MMIN     MMAX
0    256.0   6000.0
1   8000.0  32000.0
2   8000.0  32000.0
3   8000.0  32000.0
4   8000.0  16000.0
5   8000.0  32000.0
6  16000.0  32000.0

In [89]:
type(cpu[['MMIN', 'MMAX']].head(7)) # This is a DataFrame

pandas.core.frame.DataFrame

To select specific **observations (i.e. rows)** we need to pass in the corresponding indices. This operation is called *slicing*. The resulting structure is again a DataFrame.

In [90]:
cpu[0:3]  # Do not forget that Python follows 0-based indexing

vendor   MYCT    MMIN     MMAX   CACH  CHMIN  CHMAX    ERP
0  adviser  125.0   256.0   6000.0  256.0   16.0  128.0  199.0
1   amdahl   29.0  8000.0  32000.0   32.0    8.0   32.0  253.0
2   amdahl   29.0  8000.0  32000.0   32.0    8.0   32.0  253.0

In [91]:
# This is equivalent to using .iloc
cpu.iloc[0:3]

vendor   MYCT    MMIN     MMAX   CACH  CHMIN  CHMAX    ERP
0  adviser  125.0   256.0   6000.0  256.0   16.0  128.0  199.0
1   amdahl   29.0  8000.0  32000.0   32.0    8.0   32.0  253.0
2   amdahl   29.0  8000.0  32000.0   32.0    8.0   32.0  253.0

#### Filtering

Now suppose that you want to select all the observations which have an MMAX value which is higher than 35000. It is easy to do that:

In [92]:
cpu[cpu['MMAX'] > 35000]

vendor  MYCT     MMIN     MMAX   CACH  CHMIN  CHMAX     ERP
8    amdahl  23.0  16000.0  64000.0   64.0   16.0   32.0   749.0
9    amdahl  23.0  32000.0  64000.0  128.0   32.0   64.0  1238.0
198  sperry  30.0   8000.0  64000.0   96.0   12.0  176.0   919.0
199  sperry  30.0   8000.0  64000.0  128.0   12.0  176.0   978.0

Or equivalently:

In [93]:
cpu[cpu.MMAX > 35000]

vendor  MYCT     MMIN     MMAX   CACH  CHMIN  CHMAX     ERP
8    amdahl  23.0  16000.0  64000.0   64.0   16.0   32.0   749.0
9    amdahl  23.0  32000.0  64000.0  128.0   32.0   64.0  1238.0
198  sperry  30.0   8000.0  64000.0   96.0   12.0  176.0   919.0
199  sperry  30.0   8000.0  64000.0  128.0   12.0  176.0   978.0

You can also filter the data by using multiple attributes:

In [94]:
cpu[(cpu.MMAX > 35000) & (cpu.MMIN > 16000)]

vendor  MYCT     MMIN     MMAX   CACH  CHMIN  CHMAX     ERP
9  amdahl  23.0  32000.0  64000.0  128.0   32.0   64.0  1238.0

We saw before how we can select rows by passing the index numbers. This most of the time works but very often our indices are not in linear ascending order. 

There are two basic methods of indexing DataFrame structures:
* `loc`: works on labels in the index
* `iloc`: works on the position in the index (so it only takes integers)

The following example should clarify the difference between label-based indexing (`loc`) and positional indexing (`iloc`)


In [95]:
# First let's create a new dataframe
cpu_new = cpu[cpu['MMAX'] > 35000]
cpu_new

vendor  MYCT     MMIN     MMAX   CACH  CHMIN  CHMAX     ERP
8    amdahl  23.0  16000.0  64000.0   64.0   16.0   32.0   749.0
9    amdahl  23.0  32000.0  64000.0  128.0   32.0   64.0  1238.0
198  sperry  30.0   8000.0  64000.0   96.0   12.0  176.0   919.0
199  sperry  30.0   8000.0  64000.0  128.0   12.0  176.0   978.0

In [96]:
cpu_new.loc[8:10] # Looks for the rows which are labelled 8 and 9

vendor  MYCT     MMIN     MMAX   CACH  CHMIN  CHMAX     ERP
8  amdahl  23.0  16000.0  64000.0   64.0   16.0   32.0   749.0
9  amdahl  23.0  32000.0  64000.0  128.0   32.0   64.0  1238.0

In [97]:
cpu_new.iloc[0:2] # Look for the first and second rows (this yields the same result as before)

vendor  MYCT     MMIN     MMAX   CACH  CHMIN  CHMAX     ERP
8  amdahl  23.0  16000.0  64000.0   64.0   16.0   32.0   749.0
9  amdahl  23.0  32000.0  64000.0  128.0   32.0   64.0  1238.0

In [98]:
# If we try the following we will get an empty DataFrame because there are no rows with labels 0 and 1.
cpu_new.loc[0:2]

Empty DataFrame
Columns: [vendor, MYCT, MMIN, MMAX, CACH, CHMIN, CHMAX, ERP]
Index: []

In [99]:
# The result is another DataFrame
type(cpu[0:2])

pandas.core.frame.DataFrame

A very common scenario will be the following. We want to select specific observations and columns of a DataFrame and convert to a NumPy array so that we can use it for feature extraction, classification etc. This can be achieved by using the `values` method.

In [100]:
# Select the first 10 observations and the "MMIN" and "MMAX" columns only and convert to numpy array.
cpu[:10][['MMIN', 'MMAX']].values

array([[   256.,   6000.],
       [  8000.,  32000.],
       [  8000.,  32000.],
       [  8000.,  32000.],
       [  8000.,  16000.],
       [  8000.,  32000.],
       [ 16000.,  32000.],
       [ 16000.,  32000.],
       [ 16000.,  64000.],
       [ 32000.,  64000.]])

You can confirm that by using the `values` method the resulting object is a NumPy array.

### Pandas exercises

#### ========== Question 18 ==========
Load the `credit` dataset and display the dataset basic information.

In [101]:
# Your code goes here
credit_path = os.path.join(os.getcwd(), 'datasets', 'credit.csv')
credit = pd.read_csv(credit_path)
credit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 21 columns):
CheckingAccount     1001 non-null object
Duration            1001 non-null float64
CreditHistory       1001 non-null object
Purpose             1001 non-null object
CreditAmount        1001 non-null float64
SavingsAccount      1001 non-null object
YearsEmployed       1001 non-null object
InstallmentRate     1001 non-null float64
PersonalStatus      1001 non-null object
OtherDebtors        1001 non-null object
ResidentSince       1001 non-null float64
Property            1001 non-null object
Age                 1001 non-null float64
OtherPlans          1001 non-null object
Housing             1001 non-null object
NumCreditsAtBank    1001 non-null float64
Job                 1001 non-null object
Dependents          1001 non-null float64
Telephone           1001 non-null object
Foreign             1001 non-null object
Approve             1001 non-null object
dtypes: float64(7), objec

#### ========== Question 19 ==========
Display the summary statistics of the attributes of the dataset.

In [102]:
# Your code goes here
credit.describe()


Duration  CreditAmount  InstallmentRate  ResidentSince          Age  \
count  1001.000000  1.001000e+03      1001.000000    1001.000000  1001.000000   
mean     20.882118 -9.957330e+05        -7.019980       2.842158    35.217782   
std      12.070878  3.160708e+07       316.165715       1.106825    15.398264   
min       0.000000 -1.000000e+09    -10000.000000       0.000000  -293.000000   
25%      12.000000  1.364000e+03         2.000000       2.000000    27.000000   
50%      18.000000  2.319000e+03         3.000000       3.000000    33.000000   
75%      24.000000  3.972000e+03         4.000000       4.000000    42.000000   
max      72.000000  1.842400e+04         4.000000       4.000000    75.000000   

       NumCreditsAtBank   Dependents  
count       1001.000000  1001.000000  
mean           0.406593     0.969031  
std           31.656714     5.894916  
min        -1000.000000  -185.000000  
25%            1.000000     1.000000  
50%            1.000000     1.000000  
75%            2.000000     1.000000  
max            4.000000     2.000000

#### ========== Question 20 ==========
Display the last 6 instances of the dataset.

In [103]:
# Your code goes here
credit.head(6)


CheckingAccount  Duration CreditHistory     Purpose  CreditAmount  \
0              <0       0.0            ok   furniture -1.000000e+09   
1              <0       6.0      critical  television  1.169000e+03   
2            <200      48.0    ok_til_now  television  5.951000e+03   
3            none      12.0      critical   education  2.096000e+03   
4              <0      42.0    ok_til_now   furniture  7.882000e+03   
5              <0      24.0   past_delays     car_new  4.870000e+03   

  SavingsAccount YearsEmployed  InstallmentRate PersonalStatus OtherDebtors  \
0        unknown    unemployed         -10000.0  female_single         none   
1        unknown           >=7              4.0    male_single         none   
2           <100            <4              2.0         female         none   
3           <100            <7              2.0    male_single         none   
4           <100            <7              2.0    male_single    guarantor   
5           <100            <4              3.0    male_single         none   

    ...       Property    Age  OtherPlans Housing NumCreditsAtBank        Job  \
0   ...            car -293.0        none     own          -1000.0    skilled   
1   ...    real_estate   67.0        none     own              2.0    skilled   
2   ...    real_estate   22.0        none     own              1.0    skilled   
3   ...    real_estate   49.0        none     own              1.0  unskilled   
4   ...        savings   45.0        none    free              1.0    skilled   
5   ...        unknown   53.0        none    free              2.0    skilled   

  Dependents  Telephone Foreign Approve  
0     -185.0        yes      no    good  
1        1.0        yes     yes    good  
2        1.0         no     yes     bad  
3        2.0         no     yes    good  
4        2.0         no     yes    good  
5        2.0         no     yes     bad  

[6 rows x 21 columns]

#### ========== Question 21 ==========
Print the 5th observation (do not forget that Python follows 0-base indexing).

In [104]:
print(credit.iloc[4])

CheckingAccount              <0
Duration                     42
CreditHistory        ok_til_now
Purpose               furniture
CreditAmount               7882
SavingsAccount             <100
YearsEmployed                <7
InstallmentRate               2
PersonalStatus      male_single
OtherDebtors          guarantor
ResidentSince                 4
Property                savings
Age                          45
OtherPlans                 none
Housing                    free
NumCreditsAtBank              1
Job                     skilled
Dependents                    2
Telephone                    no
Foreign                     yes
Approve                    good
Name: 4, dtype: object


#### ========== Question 22 ==========
Print the standard deviation of the attribute `CreditAmount` by using the numpy method `std`. You can verify you get the correct result by inspecting the statistics table from Question 19.

In [105]:
credit['CreditAmount'].values.std()

31591288.885041825

## Matplotlib introduction

Matplotlib is a 2D python plotting library with a similar interface to MATLAB's plot engine. The library is fully compatible with NumPy which means that we can -and most of the times will- pass numpy arrays as input arguments to the various plotting functions.

There are many [resources](http://matplotlib.org/resources/index.html) for learning how to use Matplotlib. The following examples demonstrate only some basic plotting functions. When you are looking for a particular feature which you don't know yet how to implement a web search can prove very useful.

In [ ]:
# First we need to import the package and force it to render plots inside the notebook
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
# The first example creates a sine and a cosine and plots them.
X = np.linspace(-np.pi, np.pi, 256,endpoint=True) # Evenly spaced numbers over the specified interval
C, S = np.cos(X), np.sin(X) # Create a sine (S) and a cosine (C)

plt.figure(figsize=(8,5)) # Instantiates figure with a specified size
plt.plot(X,C, label='Cosine', color='blue')
plt.plot(X,S, label='Sine', color='red')
plt.legend() # Displays legend
plt.show()

In [ ]:
# Create 4 subplots and plot cosines with different colours, linestyels and linewidths.
X = np.linspace(-np.pi, np.pi, 256,endpoint=True) # Evenly spaced numbers over the specified interval
C1, C2, C3, C4 = np.cos(X), np.cos(X+0.5), np.cos(X+1.), np.cos(X+1.5)

f, ax = plt.subplots(figsize=(7,7))
plt.subplot(2,2,1)
plt.plot(X, C1)
plt.title('C1')
plt.xticks([]) # Removes xticks
plt.subplot(2,2,2)
plt.plot(X, C2, color='green',  linestyle='-.')
plt.title('C2')
plt.yticks([]) # Removes yticks
plt.subplot(2,2,3)
plt.plot(X, C3, color='k', linestyle='--')
plt.title('C3')
plt.subplot(2,2,4)
plt.plot(X, C4, color='m', linewidth = 5.)
plt.title('C4')
plt.show()

In [ ]:
# Plot a histogram and add some text
mu, sigma = 100, 15
x = mu + sigma * np.random.randn(10000) # Generate data from a normal distribution with mean mu and variance sigma

# the histogram of the data
n, bins, patches = plt.hist(x, 50, normed=1, facecolor='g', alpha=0.75)

plt.xlabel('Smarts')
plt.ylabel('Probability')
plt.title('Histogram of IQ')
plt.text(60, .025, r'$\mu=100,\ \sigma=15$') # Adds some text by using TeX
plt.axis([40, 160, 0, 0.03]) # Sets the axes limits
plt.grid(True) # Enables grid
plt.show()

### Matplotlib exercises

#### ========== Question 23 ==========
Initialise an empty figure of size (8,6). Create a scatter plot of the observations in the `credit` dataset for the attributes `Duration` and `Age` (age should be shown on the xaxis). Use black coloured markers. Label the axes accordingly by using red colour for the xaxis and green for the yaxis. Finally, add a title of your choice by using a font size of 20. 

In [ ]:
# Your code goes here


#### ========== Question 24 ==========
You should note above that there is an outlier (i.e. an observation that is very distant to the other observations). Now you think that there must be something wrong with that observation (why?) and as a next step you should remove it from both the age and duration variables and a make a scatter plot of the new data.

In [ ]:
# Your code goes here


## Seaborn

[Seaborn](https://seaborn.github.io/) is a visualisation library built on top of matplotlib which offers some aesthetic enhancement and, more importantly, provides some high-level functions for  "exploring and understanding data". Seaborn is also tightly integrated with pandas and provides support for both numpy and pandas data structures.

In the following example we will load seaborn and use its default settings to plot again the sine and cosine waves we saw earlier.

Note that this example does not actually use any seaborn functions, but as soon as the library is loaded, the Seaborn plotting style is adopted by the matplotlib.pyplot library.

In [ ]:
import seaborn as sns # Load seaborn with default settings
X = np.linspace(-np.pi, np.pi, 256,endpoint=True) # Evenly spaced numbers over the specified interval
C, S = np.cos(X), np.sin(X) # Create a sine (S) and a cosine (C)
plt.figure(figsize=(8,5))
plt.plot(X,C, label='Cosine')
plt.plot(X,S, label='Sine')
plt.legend()
plt.show()

### Seaborn implemented functions [Optional]
The Seaborn website has many great examples. Below we show a few taken directly from the website. These are just to give you a flavour of the kinds of things that Seaborn can do. You can use it as reference later; by no means should you learn this code by heart! You should definitely not worry if some of the following commands do not make sense just yet.

In [ ]:
sns.set(style="white", palette="muted", color_codes=True)
rs = np.random.RandomState(10)

# Set up the matplotlib figure
f, axes = plt.subplots(2, 2, figsize=(7, 7), sharex=True)
sns.despine(left=True)

# Generate a random univariate dataset
d = rs.normal(size=100)

# Plot a simple histogram with binsize determined automatically
sns.distplot(d, kde=False, color="b", ax=axes[0, 0])

# Plot a kernel density estimate and rug plot
sns.distplot(d, hist=False, rug=True, color="r", ax=axes[0, 1])

# Plot a filled kernel density estimate
sns.distplot(d, hist=False, color="g", kde_kws={"shade": True}, ax=axes[1, 0])

# Plot a historgram and kernel density estimate
sns.distplot(d, color="m", ax=axes[1, 1])

plt.setp(axes, yticks=[])
plt.tight_layout()

In [ ]:
sns.set(style="white")

# Generate a random correlated bivariate dataset
rs = np.random.RandomState(5)
mean = [0, 0]
cov = [(1, .5), (.5, 1)]
x1, x2 = rs.multivariate_normal(mean, cov, 500).T
x1 = pd.Series(x1, name="$X_1$")
x2 = pd.Series(x2, name="$X_2$")

# Show the joint distribution using kernel density estimation
g = sns.jointplot(x1, x2, kind="kde", size=7, space=0)

In [ ]:
sns.set(style="whitegrid", palette="pastel", color_codes=True)

# Load the example tips dataset
tips = sns.load_dataset("tips")

# Draw a nested violinplot and split the violins for easier comparison
sns.violinplot(x="day", y="total_bill", hue="sex", data=tips, split=True,
               inner="quart", palette={"Male": "b", "Female": "y"})
sns.despine(left=True)
plt.show()

In [ ]:
sns.set(style="darkgrid")

# Load the example titanic dataset
df = sns.load_dataset("titanic")

# Make a custom palette with gendered colors
pal = dict(male="#6495ED", female="#F08080")

# Show the survival proability as a function of age and sex
g = sns.lmplot(x="age", y="survived", col="sex", hue="sex", data=df,
               palette=pal, y_jitter=.02, logistic=True)
g.set(xlim=(0, 80), ylim=(-.05, 1.05))
plt.show()

In [ ]:
sns.set()

# Load the example flights dataset and convert to long-form
flights_long = sns.load_dataset("flights")
flights = flights_long.pivot("month", "year", "passengers")

# Draw a heatmap with the numeric values in each cell
sns.heatmap(flights, annot=True, fmt="d", linewidths=.5)
plt.show()

In [ ]:
sns.set(style="darkgrid")

tips = sns.load_dataset("tips")
g = sns.FacetGrid(tips, row="sex", col="time", margin_titles=True)
bins = np.linspace(0, 60, 13)
g.map(plt.hist, "total_bill", color="steelblue", bins=bins, lw=0)
plt.show()

In [ ]:
sns.set(style="ticks")

# Create a dataset with many short random walks
rs = np.random.RandomState(4)
pos = rs.randint(-1, 2, (20, 5)).cumsum(axis=1)
pos -= pos[:, 0, np.newaxis]
step = np.tile(range(5), 20)
walk = np.repeat(range(20), 5)
df = pd.DataFrame(np.c_[pos.flat, step, walk],
                  columns=["position", "step", "walk"])

# Initialize a grid of plots with an Axes for each walk
grid = sns.FacetGrid(df, col="walk", hue="walk", col_wrap=5, size=1.5)

# Draw a horizontal line to show the starting point
grid.map(plt.axhline, y=0, ls=":", c=".5")

# Draw a line plot to show the trajectory of each random walk
grid.map(plt.plot, "step", "position", marker="o", ms=4)

# Adjust the tick positions and labels
grid.set(xticks=np.arange(5), yticks=[-3, 3],
         xlim=(-.5, 4.5), ylim=(-3.5, 3.5))

# Adjust the arrangement of the plots
grid.fig.tight_layout(w_pad=1)